### ISSUE TITLE
Issue when adding a proxy

### ISSUE THREAD

**Issue by tudorchira** [igimanaloto/timpla#79]
Hi,
first of all great tool, I've used Blendid a lot and I'm very happy someone continues to carry the torch!

I'm trying to use timpla together with a Wordpress local site but when using the proxy option for browsersync it looks like it expects a index.html file so it redirects to the 404 page.

I've tested by creating a index.html page in the root folder and indeed it picks that up. Is there a way to go around this? 
Thanks

**Comment by igimanaloto** [comment]
Hey! Thanks very much for using Timpla. :)

Timpla uses https://github.com/bripkens/connect-history-api-fallback browsersync middleware to route SPAs.

To get around this, you may disable the default spa middleware:

```
configure({
  html: false,
  browserSync: {
    middlewareConfig: {
      disableSpa: true,
    },
    proxy: {
      target: 'http://wptest.test',
    },
    open: false,
  },
})
```

Let me know if you have other questions!

**Comment by tudorchira** [comment]
Thanks, that worked out great!

**Comment by igimanaloto** [comment]
No worries! Just did a minor patch, setting the proxy option via browserSyncConfig should disable the SPA middleware now :)
